Develop
mate-academy/react_phone-catalog pull request #125
Opened 2022-11-02 19:45 UTC by MAIK-01

[DEMO](https://MAIK-01.github.io/react-phone-catalog/)

2022-11-03 18:39 UTC, AlisaVlasova requested changes

2022-11-03 18:39 UTC, AlisaVlasova commented on README.md
> +[DEMO](https://MAIK-01.github.io/react-phone-catalog/)
demo doesn`t work(

2022-11-11 17:12 UTC, MAIK-01 commented on README.md
> +[DEMO](https://MAIK-01.github.io/react-phone-catalog/)
Що потрібно виправити, щоб запрацювало???

2022-11-11 17:33 UTC, MAIK-01 commented
DEMO [https://maik-01.github.io/react_phone-catalog/]

2022-11-13 08:58 UTC, TarasHoliuk commented
2nd point:
![image](https://user-images.githubusercontent.com/86923089/201513669-511d5732-106f-4d79-b4f6-718ea46801a2.png)

![image](https://user-images.githubusercontent.com/86923089/201513639-dcbedad3-bd01-4ec7-8e3b-231c275aaadd.png)
![image](https://user-images.githubusercontent.com/86923089/201513647-b27dfb66-acbe-48b1-b99f-de1abd16c2ac.png)

Sometimes it's unclear which file in styles relates to which component. It's essential to provide easy navigation through your code blocks to maintain the app.
As a possible solution, you could even create a folder for each component with the following structure (optional):
```
Component.tsx
Component.scss
index.ts
```
Re-export `Component.tsx` in `index.ts`;

2022-11-13 08:59 UTC, TarasHoliuk commented
Try to fix tests:
![image](https://user-images.githubusercontent.com/86923089/201513954-f4f77e59-d818-462f-b280-0d459578d12e.png)

2022-11-13 09:01 UTC, TarasHoliuk commented
It's better to open it in the new tab: 
![image](https://user-images.githubusercontent.com/86923089/201514007-f048753a-e052-4d62-bb15-32ff1a3a2d79.png)

2022-11-13 09:56 UTC, TarasHoliuk requested changes
Amazing job! But a fixes are needed (check comments, please)

2022-11-13 09:56 UTC, TarasHoliuk commented on src/components/Home.tsx
> +  const hotPriceProducts = useMemo(getHotPriceProducts, [products]);
to memoize functions use `useCallback` hook

2022-11-13 09:56 UTC, TarasHoliuk commented on src/components/Home.tsx
> +    return [...products].filter(product => product.age > 10);
why `age > 10`?
![image](https://user-images.githubusercontent.com/86923089/201514510-6b004440-ac30-4bdd-b114-7bff263d88ba.png)

2022-11-13 09:56 UTC, TarasHoliuk commented on src/components/TabletsPage.tsx
> +          <div className={classNames(
You are doing the same on each page. Move it to separate component

2022-11-13 09:56 UTC, TarasHoliuk commented on src/components/TabletsPage.tsx
> +          <div className={classNames(
the same: move it to a separate component and reuse on each page

2022-11-13 09:56 UTC, TarasHoliuk commented on src/components/CartItem.tsx
> +        return;
What do you think about removing the product in this case? You can move the callback from `cart_close` button to a separate function and use it here and in the mentioned button. (optional).
Or disable the button (add the corresponding styles in this case)

2022-11-13 09:56 UTC, TarasHoliuk commented on src/components/CustomSlider.jsx
> +/* eslint-disable jsx-a11y/control-has-associated-label */
try to figure out these rules (google them) and avoid `eslint-disable` if it's possible

2022-11-13 09:56 UTC, TarasHoliuk commented on src/components/Favorites.tsx
> +    if (currentPage > 1) {
redundant, since you disable the button in this case

2022-11-13 09:56 UTC, TarasHoliuk commented on src/components/SearchLink.tsx
> +      // to={{ search: getSearchWith(searchParams, { centuries: ['16', '18'] }) }}
Why did you leave these comments?

2025-01-23 12:07 UTC, closed without merging