added solution
mate-academy/react_phone-catalog pull request #199
Opened 2023-08-04 19:14 UTC by sheva10barca

[DEMO LINK](https://sheva10barca.github.io/react_phone-catalog/)

2023-08-05 08:15 UTC, sTorba24 requested changes
Good work!

1. for broken link just white page, add `not found` page please
![image](https://github.com/mate-academy/react_phone-catalog/assets/55200530/1d44c304-5539-417a-a9ba-3b60393e3146)

2023-08-05 08:15 UTC, sTorba24 commented on src/pages/TabletsPage/TabletsPage.tsx
> +        {filteredTablets.length === 0 && query && (
```suggestion
        {!filteredTablets.length && query && (
```

2023-08-05 08:15 UTC, sTorba24 commented on src/pages/TabletsPage/TabletsPage.tsx
> +        {filteredTablets.length === 0 && !query ? (
```suggestion
        {!filteredTablets.length && !query ? (
```

2023-08-05 13:06 UTC, VitaliyBondarenko1982 requested changes
Good job!
Consider some improvements.
- make responsive header and footer and fix horizontal scroll
![Screenshot from 2023-08-05 16-00-24](https://github.com/mate-academy/react_phone-catalog/assets/33029864/4067aaed-b53b-434f-b1ae-e7f699cb8c19)
![Screenshot from 2023-08-05 16-04-44](https://github.com/mate-academy/react_phone-catalog/assets/33029864/81144d8d-43c3-43a6-874d-eec80712e6ba)
- center content on phones page fot tablet and mobile width. check other pages
![Screenshot from 2023-08-05 16-03-00](https://github.com/mate-academy/react_phone-catalog/assets/33029864/f883d2eb-37b0-4f06-b550-61bba0a007f9)

2023-08-07 07:52 UTC, anastasiia-tilikina requested changes
Check comments.

Also let's fix some issues:

1. when I click on link in mobile menu it should close and show chosen page.
2. when I click on suggested product on `ProductDetailPage` it should open this page and scroll to top
3. now your carousel on mob devises is a bit confusing) let's show products in one row and jus increase or decrease number of cards depending on screen width.
![image](https://github.com/mate-academy/react_phone-catalog/assets/108538921/be26b3c3-98d2-4878-911f-f202be7de378)
4. looks like your search input doesn't allow to type in upper case. This is not desired behaviour. input value should be shown as is. transforming to lower case should be only for comparing.
(OPTIONAL)
5. Also I would suggest you to look at your `TabletsPage` and `AccessoriesPage` looks like if there were more products on those pages, they wouldn't work as desired. I mean pagination and filters. They should be rendered conditionally depending on how many products we have.
6. Also If we look closer to product pages we'll see that they're sharing the same logic) the difference only in url param and array of products that we should render. So technically it could be the same component which accepts props. It's up to you wether you want refactor this part or not though)

2023-08-07 07:52 UTC, anastasiia-tilikina commented on src/components/ProductCard/ProductCard.tsx
> +        throw new Error('Loading Error');
do not throw error in `catch` block it'll cause uncaught error in your script. Do something instead. for instance, show some error message to user.

2023-08-07 07:52 UTC, anastasiia-tilikina commented on src/components/ProductsSlider/ProductsSlider.scss
> +  // &__card {
delete comments

2023-08-07 07:52 UTC, anastasiia-tilikina commented on src/components/Search/Search.tsx
> +            onClick={handleClearQuery}
why should you put click event on img instead of button and disable linter?

2023-08-07 11:37 UTC, anastasiia-tilikina requested changes
You're doing Great job! very well done!

check my comment.
Also please check your breakpoints for media queries
in some width your layout is collapsed

![image](https://github.com/mate-academy/react_phone-catalog/assets/108538921/cf1ef796-bf39-4dd6-9274-610325b8a039)


![image](https://github.com/mate-academy/react_phone-catalog/assets/108538921/d8e0afde-cc43-4306-b4bb-9ef00859fc06)

OPTIONAL
In my opinion I'd suggest you to add smooth appearance for mobile menu

2023-08-07 11:37 UTC, anastasiia-tilikina commented on src/App.tsx
> +                  <Route
Great you did it with your product page!
Let's improve a bit more)
let's make our paths to product pages as variables for instance `:category` and make nested route. props will be passed depending on url

2023-08-08 08:50 UTC, anastasiia-tilikina requested changes
You did a really great job! 🔥

I was browsing through your app and found 2 more small bugs! Let's bring your website a bit closer to perfect)))

![image](https://github.com/mate-academy/react_phone-catalog/assets/108538921/9f7ea980-c48b-44c9-bfbd-9b528d71e1b0)

when I type some query on mobile device menu should also close once query is applied. the same with clearing it.

This link in footer leads to home page but doesn't scroll to top of the page and it looks a bit confusing. Let's add scroll to top.

![image](https://github.com/mate-academy/react_phone-catalog/assets/108538921/59229323-686c-419c-a0c7-bfaec9aaafd5)


I believe this is our last fix) everything else looks great!

2023-08-08 12:20 UTC, VitaliyBondarenko1982 approved these changes
Well done!

2025-02-09 20:01 UTC, closed without merging