Develop
mate-academy/react_phone-catalog pull request #379
Opened 2024-04-08 17:31 UTC by Vlad4567

https://vlad4567.github.io/react_phone-catalog/

2024-04-08 17:47 UTC, SanyaBratashchuk requested changes
1. 
![image](https://github.com/mate-academy/react_phone-catalog/assets/97547824/c83e6297-2764-4314-9340-d4477564c500)
2. `Add to card` button adds item to the favorites and `heart` button adds to card. Fix it
![image](https://github.com/mate-academy/react_phone-catalog/assets/97547824/fe8a71fe-8920-4aaa-9c4e-36edeb1b23be)

2024-04-08 18:30 UTC, SanyaBratashchuk requested changes
![image](https://github.com/mate-academy/react_phone-catalog/assets/97547824/cf91c617-db47-442f-84e3-327526e146d2)

2024-04-09 07:27 UTC, IvanFesenko requested changes
You should set one size for images to avoid such cases
![2024-04-09_10h13_06](https://github.com/mate-academy/react_phone-catalog/assets/61904995/a889d8d1-c4ff-432c-9dc4-a6ffdcc53d1f)

Not sure is it your issue, but some products not works as well. [example](https://vlad4567.github.io/react_phone-catalog/#/product/apple-ipad-air-4th-gen-64gb-sky-blue)
https://github.com/mate-academy/react_phone-catalog/assets/61904995/595ea491-ef21-4789-a707-ad677913aeb2

After click unliked - item should be removed from list
https://github.com/mate-academy/react_phone-catalog/assets/61904995/34ba8aa5-3d20-4c90-adf1-bc77948432c8

Align buttons
![2024-04-09_10h26_40](https://github.com/mate-academy/react_phone-catalog/assets/61904995/3520f7e3-54e5-40d9-b6ab-e83d23e520ce)

2024-04-09 14:25 UTC, anastasiiavorobiova requested changes
Great work! 
<img width="301" alt="Screenshot 2024-04-09 at 17 22 58" src="https://github.com/mate-academy/react_phone-catalog/assets/135232001/ce36b39a-7460-4f1b-890e-31f693311175">
This button doesn't work 
<img width="965" alt="Screenshot 2024-04-09 at 17 22 15" src="https://github.com/mate-academy/react_phone-catalog/assets/135232001/9b14c0d9-c007-49dc-ba63-eb8ea5290c35">
Consider fixing the product counter 
<img width="623" alt="Screenshot 2024-04-09 at 17 21 26" src="https://github.com/mate-academy/react_phone-catalog/assets/135232001/c4133d52-50f4-4971-84fa-ac8a88c36a8d">
This link should lead to the catalog page and the previous one should lead to the home page

2024-04-10 10:15 UTC, l4st1m0za approved these changes
Good job!

2026-08-06 08:05 UTC, closed without merging