React phone catalog page
mate-academy/react_phone-catalog pull request #475
Opened 2024-07-24 11:24 UTC by BodyaKutsyk

[page link](https://bodyakutsyk.github.io/react_phone-catalog/)

2024-07-24 12:03 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code
1. You need to fix these errors 
<img width="1047" alt="image" src="https://github.com/user-attachments/assets/ebb83dc7-4e6a-4725-a798-eac6385f67f1">

2. Add a favicon on the page 
<img width="112" alt="image" src="https://github.com/user-attachments/assets/5705df51-8a15-4662-b0f3-976ecf75e081">

3. Remove this b container for all links 
<img width="1278" alt="image" src="https://github.com/user-attachments/assets/674684f1-99e2-46f8-8b08-24d19308b001">

4. Add cursor pointer for all clickable elements on the page

5. When we increase or decrease products in the basket, this number is not updated near the basket icon at the top right
<img width="871" alt="image" src="https://github.com/user-attachments/assets/3e500403-ddea-4544-acd6-667f1974599b">

6. Add transition when the burger menu appears on the page 
<img width="565" alt="image" src="https://github.com/user-attachments/assets/6eb53cc6-cc15-48ac-bbd1-69e695210cf8">

2024-07-24 15:35 UTC, TarasHoliuk commented
1. I selected 4 items on the page and then selected the last (31) page. After selecting 16 items on the page got this:

![image](https://github.com/user-attachments/assets/f6f3e808-0a6c-49de-8538-0ba590a9a44c)

Set page 1 on `Items per page` select change

2. Point 5 from the previous review:

![image](https://github.com/user-attachments/assets/0138c3c7-54cc-4d1d-b8f0-d4401d8da065)

3. Light theme - Product name barely visible:
![image](https://github.com/user-attachments/assets/d634619e-b45f-420f-8d43-7f3bdde82654)

4. Optionally. It would be nice to add some padding to these links. Now it's difficult to click them:
![image](https://github.com/user-attachments/assets/8b34d431-5e8b-4cb1-8d5b-09091ac387b5)

2024-07-24 15:36 UTC, TarasHoliuk requested changes
You did a great job! BTW, skeleton looks nice 👍 
Let's add a few more fixes/improvements

2024-07-25 07:27 UTC, etojeDenys requested changes
1. It is better to show some loader in this case instead of a message that the product is not found

https://github.com/user-attachments/assets/8b01469c-4411-4aa7-bada-e29224ad399a


2. if we have more than 5 pages, it's better to show "..." and last page or something like that
<img width="613" alt="image" src="https://github.com/user-attachments/assets/785e1904-7d08-4269-8351-be60d2bad905">

3. minus looks here as disabled
<img width="312" alt="image" src="https://github.com/user-attachments/assets/68cecedb-c0c3-462d-a32d-2b5b54ab4fa2">

2024-07-25 15:12 UTC, GUSILLUS requested changes
GJ! 

1. Consider aspect ratio 
![image](https://github.com/user-attachments/assets/cf8cfd0e-5aeb-4faf-b946-9d8d8d0b3951)

2. Consider add disable status or make buttons toggle able 
![image](https://github.com/user-attachments/assets/e7a96067-aac0-4574-87cb-dfc46c3099a8)

3. Consider don't show bact to top button if you don't have scroll
![image](https://github.com/user-attachments/assets/d783129a-1747-4285-ad40-5c7b6c7a5e27)

4. Consider fixing UI of cart component
![image](https://github.com/user-attachments/assets/cd1b6b02-a853-4a77-9c13-e64a6af0c3af)

2024-07-26 07:04 UTC, volodymyr-soltys97 approved these changes
Great work 🔥

2026-07-11 18:52 UTC, closed without merging