Develop
mate-academy/react_phone-catalog pull request #489
Opened 2024-08-22 12:26 UTC by yurovych

https://yurovych.github.io/react_phone-catalog/

2024-08-22 16:11 UTC, TarasHoliuk commented
1. Fix lint errors (try to figure out each error, google it, and possible solutions; if cannot solve the problem disable the rule, or ask for help in the chat):

![image](https://github.com/user-attachments/assets/69a62daf-3ac0-4160-a4c2-9c00c2798738)

2. Same with ESlint:
![image](https://github.com/user-attachments/assets/53ee0dc4-70be-4ef6-aa40-c1cd95e36edc)

3. Add favicon

4. Bug with empty displayed pagination:
![image](https://github.com/user-attachments/assets/a1373e04-b077-43d0-bfba-39827fd7da87)

To reproduce:
- select 4 items on the page
- in pagination "scroll" to the last page and select it
- select 16 items on the page
- observe the bug.

5. Use SVG for a logo (in light theme too) for better quality:
![image](https://github.com/user-attachments/assets/e8e19e34-5c5a-42b4-a514-69b19e21f9aa)

6. These buttons should work:

![image](https://github.com/user-attachments/assets/19690f84-cca9-4ee0-bbc7-8c8b98afc3bb)

Change the current product ID based on color and capacity and set it as path (i.e. buttons should be links)

7. it would be nice to remove the product from the cart when click again (same on product details page):

![image](https://github.com/user-attachments/assets/b21eff85-a61c-44ed-8aeb-2bbe6b396534)

2024-08-22 16:12 UTC, TarasHoliuk requested changes
Wow! Theme and language change looks great!

But there are things that should be improved/fixed

2024-08-24 20:05 UTC, GUSILLUS requested changes
GJ!

1. Fix hover overlapping 
![image](https://github.com/user-attachments/assets/1147863c-5d4e-4636-b369-73d478f978ec)

2. Consider making 4 by default
![image](https://github.com/user-attachments/assets/cfc477c0-d6ea-4980-a5e6-a9829821a757)

3. You don't need this button if you don't have scroll, also hide scrollbar
![image](https://github.com/user-attachments/assets/b86bf2a7-2bdd-45e7-a5fe-8351e4fe9f9a)

4. Consider improve theme toggle UI
![image](https://github.com/user-attachments/assets/194c5d54-6f47-40d9-9daf-ca2189218848)

2024-08-25 09:34 UTC, vadiimvooo requested changes
Good job, a few things to improve:
1. Remove pagination on load
![image](https://github.com/user-attachments/assets/51e5b884-563b-456e-9ca7-4edd1cecde95)
2.There is a bug when on first load there are no footer
![image](https://github.com/user-attachments/assets/75c93cc5-414b-443c-a46f-386b9757f163)

2024-08-25 11:13 UTC, yurovych commented
Can you try again to check the bug with "no footer on first load", because I think it happend as an accident, cause I try it on different devices and I don't have any problem with this.
All the rest was fixed

2024-08-25 13:00 UTC, GUSILLUS requested changes
GJ!

1. Center items and reduce gap
![image](https://github.com/user-attachments/assets/0e8cdfdd-c755-4734-8a07-85a2485e46bb)

2. Arrow button need to change pages not to scroll it
![image](https://github.com/user-attachments/assets/8ff7418b-084c-4b5a-bde3-e2dba3f7ca21)

3. Don't have scroll until I click on the page
![image](https://github.com/user-attachments/assets/9e098d73-3164-411a-9d9d-521aa1d255e6)

2024-08-28 06:22 UTC, etojeDenys requested changes
looks good, but I cannot open the link to some product
https://yurovych.github.io/react_phone-catalog/#/phones/apple-iphone-14-256gb-midnight

can you do that?

2024-08-29 12:26 UTC, anastasiiavorobiova approved these changes
Awesome!

2025-06-11 09:48 UTC, closed without merging