want to help
mate-academy/react_phone-catalog pull request #493
Opened 2024-08-28 17:17 UTC by BoGoBooM

I have been trying to fix the problems in this assignment for several hours now, but nothing is working. I don't know how to fix it and I need help

2024-08-28 17:38 UTC, TarasHoliuk requested changes
Please, ask for help in the fe_chat on Mate Academy platform (or join the next Q&A session). PR is not the right place for it - a mentor sees your question only when you request review. But to solve the problem you need some dialog 🙂

2024-08-29 15:55 UTC, BoGoBooM commented
Here's dem link:
[Demo](https://bogoboom.github.io/react_phone-catalog/)

2024-08-29 16:15 UTC, SanyaBratashchuk requested changes
1. set 1-st page as active on `itemsOnPage` change
2. quantity and price can't be negative 
![image](https://github.com/user-attachments/assets/68af80b1-415c-4579-8384-7861cdde07a5)

2024-09-02 12:36 UTC, BoGoBooM commented
I hope I fixed all the issues you found in the previous commit

2024-09-02 15:28 UTC, TarasHoliuk requested changes
You did a great job! Almost done, but a few more improvements/fixes are required

2024-09-03 19:15 UTC, SanyaBratashchuk approved these changes

2025-02-17 11:44 UTC, closed without merging